services:
  web:
    container_name: contentor-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      # - ./.env.template:/app/.env:ro
      - ./app/static:/app/static

    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static
    depends_on:
      - web
  